foleys_gui_magic: StyleTextPropertyComponent Class Reference
StyleTextPropertyComponent Class Reference
#include <foleys_StyleTextPropertyComponent.h>
Public Member Functions
StyleTextPropertyComponent (MagicGUIBuilder &builderToUse, juce::Identifier propertyToUse, juce::ValueTree &nodeToUse)
void refresh () override
Public Member Functions inherited from StylePropertyComponent
StylePropertyComponent (MagicGUIBuilder &builder, juce::Identifier property, juce::ValueTree &node)
~StylePropertyComponent () override
void paint (juce::Graphics &g) override
void resized () override
void mouseDoubleClick (const juce::MouseEvent &event) override
Additional Inherited Members
Static Public Member Functions inherited from StylePropertyComponent
static StylePropertyComponent * createComponent (MagicGUIBuilder &builder, SettableProperty &property, juce::ValueTree &node)
Protected Member Functions inherited from StylePropertyComponent
juce::var lookupValue ()
Protected Attributes inherited from StylePropertyComponent
MagicGUIBuilder & builder
juce::Identifier property
juce::ValueTree node
juce::ValueTree inheritedFrom
std::unique_ptr< juce::Component > editor
juce::TextButton remove { "X" }
Constructor & Destructor Documentation
StyleTextPropertyComponent()
StyleTextPropertyComponent (MagicGUIBuilder & builderToUse, juce::Identifier propertyToUse, juce::ValueTree & nodeToUse)
References StylePropertyComponent::builder, StylePropertyComponent::editor, MagicGUIBuilder::getUndoManager(), StylePropertyComponent::node, StylePropertyComponent::property, and StyleTextPropertyComponent::refresh().
Member Function Documentation
refresh()
void refresh () override
References StylePropertyComponent::builder, StylePropertyComponent::editor, MagicGUIBuilder::getUndoManager(), StylePropertyComponent::inheritedFrom, StylePropertyComponent::lookupValue(), StylePropertyComponent::node, and StylePropertyComponent::property.
Referenced by StyleTextPropertyComponent::StyleTextPropertyComponent().
The documentation for this class was generated from the following files:
foleys_StyleTextPropertyComponent.h
foleys_StyleTextPropertyComponent.cpp