foleys_gui_magic: XYDraggerItem Class Reference
XYDraggerItem Class Reference
Public Member Functions
XYDraggerItem (MagicGUIBuilder &builder, const juce::ValueTree &node)
void update () override
In update() the ValueTree properties should be used to set all properties to the component.
std::vector< SettableProperty > getSettableProperties () const override
Override this to return each settable option the designer should be able to configure on your component.
juce::Component * getWrappedComponent () override
Allows accessing the Component inside that GuiItem.
Public Member Functions inherited from GuiItem
GuiItem (MagicGUIBuilder &builder, juce::ValueTree node)
~GuiItem () override
virtual void updateColours ()
Set colours in the wrapped Component to the value from the stylesheet and palette.
void setColourTranslation (std::vector< std::pair< juce::String, int > > mapping)
For each factory you can register a translation table, which will forward the colours from the Stylesheet to the Components.
juce::StringArray getColourNames () const
Return the names of configurable colours.
virtual juce::String getControlledParameterID (juce::Point< int >)
Returns the parameterID that is controlled from this component.
juce::var getProperty (const juce::Identifier &property)
Look up a value through the DOM and CSS.
MagicGUIState & getMagicState ()
virtual GuiItem * findGuiItemWithId (const juce::String &name)
Lookup a Component through the tree.
void updateInternal ()
Reread properties from the config ValueTree.
void paint (juce::Graphics &g) final
void resized () override
virtual bool isContainer () const
virtual void createSubComponents ()
virtual void updateLayout ()
This will trigger a recalculation of the children layout regardless of resized.
LayoutType getParentsLayoutType () const
Returns the layout type this item is managed by.
void configureFlexBoxItem (const juce::ValueTree &node)
Parse the values and set it to the FlexBox::Item for layouting.
void configurePosition (const juce::ValueTree &node)
juce::Rectangle< int > resolvePosition (juce::Rectangle< int > parent)
Calculates the position according to the parent area.
juce::Rectangle< int > getClientBounds () const
Returns the bounds of the wrapped Component.
juce::String getTabCaption (const juce::String &defaultName) const
juce::Colour getTabColour () const
juce::FlexItem & getFlexItem ()
void itemDragEnter (const juce::DragAndDropTarget::SourceDetails &details) override
void itemDragExit (const juce::DragAndDropTarget::SourceDetails &details) override
void paintOverChildren (juce::Graphics &g) override
virtual GuiItem * findGuiItem (const juce::ValueTree &node)
Seeks recursively for a GuiItem.
bool isInterestedInDragSource (const juce::DragAndDropTarget::SourceDetails &dragSourceDetails) override
void itemDropped (const juce::DragAndDropTarget::SourceDetails &dragSourceDetails) override
Static Public Attributes
static const juce::Identifier pCrosshair { "xy-crosshair" }
static const juce::StringArray pCrosshairTypes { "no-crosshair", "vertical", "horizontal", "crosshair" }
static const juce::Identifier pRadius { "xy-radius" }
static const juce::Identifier pWheelParameter { "wheel-parameter" }
static const juce::Identifier pContextParameter { "right-click" }
static const juce::Identifier pSenseFactor { "xy-sense-factor" }
static const juce::Identifier pJumpToClick { "xy-jump-to-click" }
Additional Inherited Members
Public Attributes inherited from GuiItem
MagicGUIBuilder & magicBuilder
Protected Attributes inherited from GuiItem
juce::ValueTree configNode
Decorator decorator
juce::FlexItem flexItem { juce::FlexItem (*this).withFlex (1.0f) }
std::vector< std::pair< juce::String, int > > colourTranslation
Constructor & Destructor Documentation
XYDraggerItem()
XYDraggerItem (MagicGUIBuilder & builder, const juce::ValueTree & node)
References GuiItem::setColourTranslation(), XYDragComponent::xyDotColourId, XYDragComponent::xyDotOverColourId, XYDragComponent::xyHorizontalColourId, XYDragComponent::xyHorizontalOverColourId, XYDragComponent::xyVerticalColourId, and XYDragComponent::xyVerticalOverColourId.
Member Function Documentation
update()
void update () override virtual
In update() the ValueTree properties should be used to set all properties to the component.
You can use the magicBuilder to resolve properties from CSS. The Colours will be handled by default.
Implements GuiItem.
References GuiItem::configNode, GuiItem::getMagicState(), GuiItem::getProperty(), XYDraggerItem::pContextParameter, XYDraggerItem::pCrosshair, XYDraggerItem::pCrosshairTypes, XYDraggerItem::pJumpToClick, XYDraggerItem::pRadius, XYDraggerItem::pSenseFactor, XYDraggerItem::pWheelParameter, XYDragComponent::setCrossHair(), XYDragComponent::setJumpToClick(), XYDragComponent::setParameterX(), XYDragComponent::setParameterY(), XYDragComponent::setRadius(), XYDragComponent::setRightClickParameter(), XYDragComponent::setSenseFactor(), and XYDragComponent::setWheelParameter().
getSettableProperties()
std::vector< SettableProperty > getSettableProperties () const override virtual
Override this to return each settable option the designer should be able to configure on your component.
Reimplemented from GuiItem.
References SettableProperty::Choice, GuiItem::configNode, MagicGUIBuilder::createChoicesMenuLambda(), MagicGUIBuilder::createParameterMenuLambda(), GuiItem::magicBuilder, SettableProperty::Number, XYDraggerItem::pContextParameter, XYDraggerItem::pCrosshair, XYDraggerItem::pCrosshairTypes, XYDraggerItem::pJumpToClick, XYDraggerItem::pRadius, XYDraggerItem::pSenseFactor, XYDraggerItem::pWheelParameter, and SettableProperty::Toggle.
getWrappedComponent()
juce::Component * getWrappedComponent () override virtual
Allows accessing the Component inside that GuiItem.
Don't keep this pointer!
Implements GuiItem.
Member Data Documentation
pCrosshair
const juce::Identifier pCrosshair { "xy-crosshair" } static
Referenced by XYDraggerItem::getSettableProperties(), and XYDraggerItem::update().
pCrosshairTypes
const juce::StringArray pCrosshairTypes { "no-crosshair", "vertical", "horizontal", "crosshair" } static
Referenced by XYDraggerItem::getSettableProperties(), and XYDraggerItem::update().
pRadius
const juce::Identifier pRadius { "xy-radius" } static
Referenced by XYDraggerItem::getSettableProperties(), and XYDraggerItem::update().
pWheelParameter
const juce::Identifier pWheelParameter { "wheel-parameter" } static
Referenced by XYDraggerItem::getSettableProperties(), and XYDraggerItem::update().
pContextParameter
const juce::Identifier pContextParameter { "right-click" } static
Referenced by XYDraggerItem::getSettableProperties(), and XYDraggerItem::update().
pSenseFactor
const juce::Identifier pSenseFactor { "xy-sense-factor" } static
Referenced by XYDraggerItem::getSettableProperties(), and XYDraggerItem::update().
pJumpToClick
const juce::Identifier pJumpToClick { "xy-jump-to-click" } static
Referenced by XYDraggerItem::getSettableProperties(), and XYDraggerItem::update().
The documentation for this class was generated from the following file:
foleys_MagicJUCEFactories.cpp