foleys_gui_magic: ParameterManager Class Reference
ParameterManager Class Reference
#include <foleys_ParameterManager.h>
Public Member Functions
ParameterManager (juce::AudioProcessor &processor)
juce::RangedAudioParameter * getParameter (const juce::String &paramID)
juce::StringArray getParameterNames () const
void updateParameterMap ()
void saveParameterValues (juce::ValueTree &tree)
void loadParameterValues (juce::ValueTree &tree)
Static Public Attributes
static juce::Identifier nodeName { "PARAM" }
static juce::Identifier nodeId { "id" }
static juce::Identifier nodeValue { "value" }
Constructor & Destructor Documentation
ParameterManager()
ParameterManager (juce::AudioProcessor & processor)
References ParameterManager::updateParameterMap().
Member Function Documentation
getParameter()
juce::RangedAudioParameter * getParameter (const juce::String & paramID)
Referenced by MagicProcessorState::getParameter(), and ParameterManager::loadParameterValues().
getParameterNames()
juce::StringArray getParameterNames () const
Referenced by MagicProcessorState::getParameterNames().
updateParameterMap()
void updateParameterMap ()
Referenced by ParameterManager::loadParameterValues(), ParameterManager::ParameterManager(), ParameterManager::saveParameterValues(), and MagicProcessorState::updateParameterMap().
saveParameterValues()
void saveParameterValues (juce::ValueTree & tree)
References ParameterManager::nodeId, ParameterManager::nodeName, ParameterManager::nodeValue, and ParameterManager::updateParameterMap().
Referenced by MagicProcessorState::getStateInformation().
loadParameterValues()
void loadParameterValues (juce::ValueTree & tree)
References ParameterManager::getParameter(), ParameterManager::nodeId, ParameterManager::nodeName, ParameterManager::nodeValue, and ParameterManager::updateParameterMap().
Referenced by MagicProcessorState::setStateInformation().
Member Data Documentation
nodeName
juce::Identifier nodeName { "PARAM" } static
Referenced by ParameterManager::loadParameterValues(), and ParameterManager::saveParameterValues().
nodeId
juce::Identifier nodeId { "id" } static
Referenced by ParameterManager::loadParameterValues(), and ParameterManager::saveParameterValues().
nodeValue
juce::Identifier nodeValue { "value" } static
Referenced by ParameterManager::loadParameterValues(), and ParameterManager::saveParameterValues().
The documentation for this class was generated from the following files:
foleys_ParameterManager.h
foleys_ParameterManager.cpp