foleys_gui_magic: XYDragComponent Class Reference
XYDragComponent Class Reference
This is a 2D parameter dragging component.
#include <foleys_XYDragComponent.h>
Inherits Component, and SettableTooltipClient.
Public Types
enum ColourIds {
xyDotColourId = 0x2002000 , xyDotOverColourId , xyHorizontalColourId , xyHorizontalOverColourId ,
xyVerticalColourId , xyVerticalOverColourId
}
Public Member Functions
XYDragComponent ()
void setCrossHair (bool horizontal, bool vertical)
This sets the crosshair lines on and off.
void paint (juce::Graphics &g) override
void setParameterX (juce::RangedAudioParameter *parameter)
void setParameterY (juce::RangedAudioParameter *parameter)
void setWheelParameter (juce::RangedAudioParameter *parameter)
void setRightClickParameter (juce::RangedAudioParameter *parameter)
void setRadius (float radius)
void setSenseFactor (float factor)
void setJumpToClick (bool shouldJumpToClick)
bool hitTest (int x, int y) override
void mouseDown (const juce::MouseEvent &) override
void mouseMove (const juce::MouseEvent &) override
void mouseDrag (const juce::MouseEvent &) override
void mouseUp (const juce::MouseEvent &) override
void mouseWheelMove (const juce::MouseEvent &, const juce::MouseWheelDetails &) override
void mouseEnter (const juce::MouseEvent &) override
void mouseExit (const juce::MouseEvent &) override
Detailed Description
This is a 2D parameter dragging component.
Member Enumeration Documentation
ColourIds
enum ColourIds
Enumerator
xyDotColourId
xyDotOverColourId
xyHorizontalColourId
xyHorizontalOverColourId
xyVerticalColourId
xyVerticalOverColourId
Constructor & Destructor Documentation
XYDragComponent()
XYDragComponent ()
References ParameterAttachment< ValueType >::onParameterChangedAsync, XYDragComponent::xyDotColourId, XYDragComponent::xyDotOverColourId, XYDragComponent::xyHorizontalColourId, XYDragComponent::xyHorizontalOverColourId, XYDragComponent::xyVerticalColourId, and XYDragComponent::xyVerticalOverColourId.
Member Function Documentation
setCrossHair()
void setCrossHair (bool horizontal, bool vertical)
This sets the crosshair lines on and off.
Parameters
horizontal switches the horizontal line visible and enables vertical drags
vertical switches the vertical line visible and enables horizontal drags
Referenced by XYDraggerItem::update().
paint()
void paint (juce::Graphics & g) override
References XYDragComponent::xyDotColourId, XYDragComponent::xyDotOverColourId, XYDragComponent::xyHorizontalColourId, XYDragComponent::xyHorizontalOverColourId, XYDragComponent::xyVerticalColourId, and XYDragComponent::xyVerticalOverColourId.
setParameterX()
void setParameterX (juce::RangedAudioParameter * parameter)
References ParameterAttachment< ValueType >::attachToParameter().
Referenced by XYDraggerItem::update().
setParameterY()
void setParameterY (juce::RangedAudioParameter * parameter)
References ParameterAttachment< ValueType >::attachToParameter().
Referenced by XYDraggerItem::update().
setWheelParameter()
void setWheelParameter (juce::RangedAudioParameter * parameter)
Referenced by XYDraggerItem::update().
setRightClickParameter()
void setRightClickParameter (juce::RangedAudioParameter * parameter)
Referenced by XYDraggerItem::update().
setRadius()
void setRadius (float radius)
Referenced by XYDraggerItem::update().
setSenseFactor()
void setSenseFactor (float factor)
Referenced by XYDraggerItem::update().
setJumpToClick()
void setJumpToClick (bool shouldJumpToClick)
Referenced by XYDraggerItem::update().
hitTest()
bool hitTest (int x, int y) override
mouseDown()
void mouseDown (const juce::MouseEvent & event) override
References ParameterAttachment< ValueType >::beginGesture(), and ParameterAttachment< ValueType >::setNormalisedValue().
mouseMove()
void mouseMove (const juce::MouseEvent & event) override
mouseDrag()
void mouseDrag (const juce::MouseEvent & event) override
References ParameterAttachment< ValueType >::setNormalisedValue().
mouseUp()
void mouseUp (const juce::MouseEvent & event) override
References ParameterAttachment< ValueType >::endGesture().
mouseWheelMove()
void mouseWheelMove (const juce::MouseEvent & event, const juce::MouseWheelDetails & details) override
mouseEnter()
void mouseEnter (const juce::MouseEvent & event) override
mouseExit()
void mouseExit (const juce::MouseEvent &) override
The documentation for this class was generated from the following files:
foleys_XYDragComponent.h
foleys_XYDragComponent.cpp