foleys_gui_magic: MagicLevelMeter Class Reference
MagicLevelMeter Class Reference
#include <foleys_MagicLevelMeter.h>
Inherits Component, SettableTooltipClient, and Timer.
Classes
struct LookAndFeelMethods
Public Types
enum ColourIds {
backgroundColourId = 0x2002100 , barBackgroundColourId , barFillColourId , outlineColourId ,
tickmarkColourId
}
Public Member Functions
MagicLevelMeter ()
void paint (juce::Graphics &g) override
void setLevelSource (MagicLevelSource *newSource)
void timerCallback () override
void lookAndFeelChanged () override
Member Enumeration Documentation
ColourIds
enum ColourIds
Enumerator
backgroundColourId
barBackgroundColourId
barFillColourId
outlineColourId
tickmarkColourId
Constructor & Destructor Documentation
MagicLevelMeter()
MagicLevelMeter ()
References backgroundColourId, barBackgroundColourId, barFillColourId, lookAndFeelChanged(), outlineColourId, and tickmarkColourId.
Referenced by MagicLevelMeter::LookAndFeelMethods::drawMagicLevelMeter().
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
setLevelSource()
void setLevelSource (MagicLevelSource * newSource)
timerCallback()
void timerCallback () override
lookAndFeelChanged()
void lookAndFeelChanged () override
Referenced by MagicLevelMeter().
The documentation for this class was generated from the following files:
foleys_MagicLevelMeter.h
foleys_MagicLevelMeter.cpp