foleys_gui_magic: StyleChoicePropertyComponent Class Reference
StyleChoicePropertyComponent Class Reference
#include <foleys_StyleChoicePropertyComponent.h>
Public Member Functions
StyleChoicePropertyComponent (MagicGUIBuilder &builderToUse, juce::Identifier propertyToUse, juce::ValueTree &nodeToUse, juce::StringArray choices)
StyleChoicePropertyComponent (MagicGUIBuilder &builderToUse, juce::Identifier propertyToUse, juce::ValueTree &nodeToUse, std::function< void(juce::ComboBox &)> menuCreationLambda)
void refresh () override
Public Member Functions inherited from StylePropertyComponent
StylePropertyComponent (MagicGUIBuilder &builder, juce::Identifier property, juce::ValueTree &node)
~StylePropertyComponent () override
void paint (juce::Graphics &g) override
void resized () override
void mouseDoubleClick (const juce::MouseEvent &event) override
Additional Inherited Members
Static Public Member Functions inherited from StylePropertyComponent
static StylePropertyComponent * createComponent (MagicGUIBuilder &builder, SettableProperty &property, juce::ValueTree &node)
Protected Member Functions inherited from StylePropertyComponent
juce::var lookupValue ()
Protected Attributes inherited from StylePropertyComponent
MagicGUIBuilder & builder
juce::Identifier property
juce::ValueTree node
juce::ValueTree inheritedFrom
std::unique_ptr< juce::Component > editor
juce::TextButton remove { "X" }
Constructor & Destructor Documentation
StyleChoicePropertyComponent() [1/2]
StyleChoicePropertyComponent (MagicGUIBuilder & builderToUse, juce::Identifier propertyToUse, juce::ValueTree & nodeToUse, juce::StringArray choices)
References StylePropertyComponent::StylePropertyComponent().
StyleChoicePropertyComponent() [2/2]
StyleChoicePropertyComponent (MagicGUIBuilder & builderToUse, juce::Identifier propertyToUse, juce::ValueTree & nodeToUse, std::function< void(juce::ComboBox &)> menuCreationLambda)
References StylePropertyComponent::StylePropertyComponent().
Member Function Documentation
refresh()
void refresh () override
References StylePropertyComponent::builder, StylePropertyComponent::editor, StylePropertyComponent::inheritedFrom, StylePropertyComponent::lookupValue(), StylePropertyComponent::node, and StylePropertyComponent::property.
The documentation for this class was generated from the following files:
foleys_StyleChoicePropertyComponent.h
foleys_StyleChoicePropertyComponent.cpp