foleys_gui_magic: MouseLambdas Class Reference
MouseLambdas Class Reference
#include <foleys_MouseLambdas.h>
Inherits MouseListener.
Public Member Functions
MouseLambdas ()=default
void attachTo (juce::Component *component)
~MouseLambdas () override
void mouseDown (const juce::MouseEvent &event) override
void mouseUp (const juce::MouseEvent &event) override
void mouseDoubleClick (const juce::MouseEvent &event) override
Public Attributes
std::function< void(const juce::MouseEvent &) onMouseDown)
std::function< void(const juce::MouseEvent &) onMouseUp)
std::function< void(const juce::MouseEvent &) onMouseDoubleClick)
Constructor & Destructor Documentation
MouseLambdas()
MouseLambdas () default
~MouseLambdas()
~MouseLambdas () override
Member Function Documentation
attachTo()
void attachTo (juce::Component * component)
Referenced by StyleColourPropertyComponent::StyleColourPropertyComponent(), and StyleGradientPropertyComponent::StyleGradientPropertyComponent().
mouseDown()
void mouseDown (const juce::MouseEvent & event) override
References MouseLambdas::onMouseDown.
mouseUp()
void mouseUp (const juce::MouseEvent & event) override
References MouseLambdas::onMouseUp.
mouseDoubleClick()
void mouseDoubleClick (const juce::MouseEvent & event) override
References MouseLambdas::onMouseDoubleClick.
Member Data Documentation
onMouseDown
std::function<void(const juce::MouseEvent&) onMouseDown)
Referenced by MouseLambdas::mouseDown(), StyleColourPropertyComponent::StyleColourPropertyComponent(), and StyleGradientPropertyComponent::StyleGradientPropertyComponent().
onMouseUp
std::function<void(const juce::MouseEvent&) onMouseUp)
Referenced by MouseLambdas::mouseUp().
onMouseDoubleClick
std::function<void(const juce::MouseEvent&) onMouseDoubleClick)
Referenced by MouseLambdas::mouseDoubleClick().
The documentation for this class was generated from the following file:
foleys_MouseLambdas.h