foleys_gui_magic: Decorator Class Reference
Decorator Class Reference
#include <foleys_Decorator.h>
Classes
struct ClientBounds
Public Member Functions
Decorator ()=default
void configure (MagicGUIBuilder &builder, const juce::ValueTree &node)
This will get the necessary information from the stylesheet, using inheritance of nodes if needed, to set the margins/borders etc.
void reset ()
void updateColours (MagicGUIBuilder &builder, const juce::ValueTree &node)
void drawDecorator (juce::Graphics &g, juce::Rectangle< int > bounds)
Decorator::ClientBounds getClientBounds (juce::Rectangle< int > overallBounds) const
juce::String getTabCaption (const juce::String &defaultName) const
juce::Colour getTabColour () const
juce::Colour getBackgroundColour () const
Constructor & Destructor Documentation
Decorator()
Decorator () default
Member Function Documentation
configure()
void configure (MagicGUIBuilder & builder, const juce::ValueTree & node)
This will get the necessary information from the stylesheet, using inheritance of nodes if needed, to set the margins/borders etc.
for the GuiItem.
References MagicGUIBuilder::getStyleProperty(), MagicGUIBuilder::getStylesheet(), and GradientBackground::setup().
Referenced by GuiItem::updateInternal().
reset()
void reset ()
References GradientBackground::clear().
updateColours()
void updateColours (MagicGUIBuilder & builder, const juce::ValueTree & node)
References MagicGUIBuilder::getStyleProperty(), and MagicGUIBuilder::getStylesheet().
Referenced by Container::updateColours(), and GuiItem::updateColours().
drawDecorator()
void drawDecorator (juce::Graphics & g, juce::Rectangle< int > bounds)
References GradientBackground::drawGradient(), Decorator::getClientBounds(), GradientBackground::isEmpty(), and Box< T >::reducedRect().
Referenced by GuiItem::paint().
getClientBounds()
Decorator::ClientBounds getClientBounds (juce::Rectangle< int > overallBounds) const
References Box< T >::reducedRect().
Referenced by Decorator::drawDecorator(), and GuiItem::getClientBounds().
getTabCaption()
juce::String getTabCaption (const juce::String & defaultName) const
Referenced by GuiItem::getTabCaption().
getTabColour()
juce::Colour getTabColour () const
Referenced by GuiItem::getTabColour().
getBackgroundColour()
juce::Colour getBackgroundColour () const
Referenced by Container::updateLayout().
The documentation for this class was generated from the following files:
foleys_Decorator.h
foleys_Decorator.cpp