foleys_gui_magic: PropertiesEditor Class Reference
PropertiesEditor Class Reference
#include <foleys_PropertiesEditor.h>
Inherits Component, and Listener.
Public Member Functions
PropertiesEditor (MagicGUIBuilder &builder)
void setStyle (juce::ValueTree style)
void setNodeToEdit (juce::ValueTree node)
juce::ValueTree & getNodeToEdit ()
void createNewClass ()
void deleteClass (const juce::String &name)
void addNodeProperties ()
void addDecoratorProperties ()
void addTypeProperties (juce::Identifier type, juce::Array< juce::PropertyComponent * > additional)
void addFlexItemProperties ()
void addContainerProperties ()
void addPaletteColours ()
void paint (juce::Graphics &) override
void resized () override
MagicGUIBuilder & getMagicBuilder ()
Constructor & Destructor Documentation
PropertiesEditor()
PropertiesEditor (MagicGUIBuilder & builder)
References Stylesheet::addPaletteEntry(), foleys::ClassEdit, MagicGUIBuilder::getStylesheet(), foleys::NodeEdit, foleys::PaletteEdit, PropertiesEditor::setNodeToEdit(), and foleys::TypeEdit.
Member Function Documentation
setStyle()
void setStyle (juce::ValueTree style)
Referenced by ToolBox::stateWasReloaded().
setNodeToEdit()
void setNodeToEdit (juce::ValueTree node)
References PropertiesEditor::addContainerProperties(), PropertiesEditor::addDecoratorProperties(), PropertiesEditor::addFlexItemProperties(), PropertiesEditor::addNodeProperties(), PropertiesEditor::addPaletteColours(), PropertiesEditor::addTypeProperties(), MagicGUIBuilder::getFactoryNames(), and MagicGUIBuilder::getStylesheet().
Referenced by PropertiesEditor::PropertiesEditor(), ToolBox::setNodeToEdit(), and ToolBox::setSelectedNode().
getNodeToEdit()
juce::ValueTree & getNodeToEdit ()
createNewClass()
void createNewClass ()
deleteClass()
void deleteClass (const juce::String & name)
References Stylesheet::deleteStyleClass(), MagicGUIBuilder::getGuiRootNode(), MagicGUIBuilder::getStylesheet(), and MagicGUIBuilder::removeStyleClassReferences().
addNodeProperties()
void addNodeProperties ()
References MagicGUIBuilder::createPropertiesMenuLambda, Stylesheet::getAllClassesNames(), MagicGUIBuilder::getGuiRootNode(), and MagicGUIBuilder::getStylesheet().
Referenced by PropertiesEditor::setNodeToEdit().
addDecoratorProperties()
void addDecoratorProperties ()
References MagicGUIBuilder::createPropertiesMenuLambda, Stylesheet::getLookAndFeelNames(), and MagicGUIBuilder::getStylesheet().
Referenced by PropertiesEditor::setNodeToEdit().
addTypeProperties()
void addTypeProperties (juce::Identifier type, juce::Array< juce::PropertyComponent * > additional)
References StylePropertyComponent::createComponent(), and MagicGUIBuilder::createGuiItem().
Referenced by PropertiesEditor::setNodeToEdit().
addFlexItemProperties()
void addFlexItemProperties ()
Referenced by PropertiesEditor::setNodeToEdit().
addContainerProperties()
void addContainerProperties ()
References MagicGUIBuilder::createPropertiesMenuLambda.
Referenced by PropertiesEditor::setNodeToEdit().
addPaletteColours()
void addPaletteColours ()
Referenced by PropertiesEditor::setNodeToEdit().
paint()
void paint (juce::Graphics & g) override
resized()
void resized () override
getMagicBuilder()
MagicGUIBuilder & getMagicBuilder ()
The documentation for this class was generated from the following files:
foleys_PropertiesEditor.h
foleys_PropertiesEditor.cpp