foleys_gui_magic: MagicPluginEditor Class Reference
MagicPluginEditor Class Reference
This is a generic AudioProcessorEditor, that is completely defined and styled by drag and drop.
#include <foleys_MagicPluginEditor.h>
Inherits AudioProcessorEditor, and DragAndDropContainer.
Public Member Functions
MagicPluginEditor (MagicProcessorState &processorState, std::unique_ptr< MagicGUIBuilder > builder={})
Create an AudioProcessorEditor populated from a MagicGUIBuilder.
~MagicPluginEditor () override
void setConfigTree (const juce::ValueTree &config)
Setup a GUI from a previously stored ValueTree.
MagicGUIBuilder & getGUIBuilder ()
Grants access to the MagicGUIBuilder.
void paint (juce::Graphics &g) override
void resized () override
Detailed Description
This is a generic AudioProcessorEditor, that is completely defined and styled by drag and drop.
There is an XML representation, that can be baked into the project using the BinaryData of Projucer.
Constructor & Destructor Documentation
MagicPluginEditor()
MagicPluginEditor (MagicProcessorState & processorState, std::unique_ptr< MagicGUIBuilder > builder = {})
Create an AudioProcessorEditor populated from a MagicGUIBuilder.
References MagicGUIState::getGuiTree(), MagicGUIState::getValueTree(), and MagicPluginEditor::setConfigTree().
~MagicPluginEditor()
~MagicPluginEditor () override
Member Function Documentation
setConfigTree()
void setConfigTree (const juce::ValueTree & config)
Setup a GUI from a previously stored ValueTree.
Parameters
config the ValueTree that defines the Stylesheet, colour palette and GUI components of the editor
Referenced by MagicPluginEditor::MagicPluginEditor().
getGUIBuilder()
MagicGUIBuilder & getGUIBuilder ()
Grants access to the MagicGUIBuilder.
paint()
void paint (juce::Graphics & g) override
resized()
void resized () override
References MagicProcessorState::setLastEditorSize().
The documentation for this class was generated from the following files:
foleys_MagicPluginEditor.h
foleys_MagicPluginEditor.cpp