foleys_gui_magic: MidiParameterMapper Class Reference
MidiParameterMapper Class Reference
The MidiParameterMapper allows to connect CC values to RangedAudioParameters.
#include <foleys_MidiParameterMapper.h>
Inherits Listener.
Public Member Functions
MidiParameterMapper (MagicProcessorState &state)
~MidiParameterMapper () override
void processMidiBuffer (juce::MidiBuffer &buffer)
void mapMidiController (int cc, const juce::String &parameterID)
void unmapMidiController (int cc, const juce::String &parameterID)
void unmapAllMidiController (int cc)
int getLastController () const
juce::ValueTree getMappingSettings ()
Detailed Description
The MidiParameterMapper allows to connect CC values to RangedAudioParameters.
Constructor & Destructor Documentation
MidiParameterMapper()
MidiParameterMapper (MagicProcessorState & state)
~MidiParameterMapper()
~MidiParameterMapper () override
Member Function Documentation
processMidiBuffer()
void processMidiBuffer (juce::MidiBuffer & buffer)
Get Midi CC messages and set parameters accordingly
Parameters
buffer the last midi events
Referenced by MagicProcessorState::processMidiBuffer().
mapMidiController()
void mapMidiController (int cc, const juce::String & parameterID)
Map a MIDI CC to a parameter
Parameters
cc the MIDI CC number to map
parameterID the parameterID to map to
References MidiParameterMapper::getMappingSettings().
Referenced by MagicProcessorState::mapMidiController().
unmapMidiController()
void unmapMidiController (int cc, const juce::String & parameterID)
Remove a specific mapping
Parameters
cc the MIDI CC number to map
parameterID the parameterID to unmap
References MidiParameterMapper::getMappingSettings().
unmapAllMidiController()
void unmapAllMidiController (int cc)
Remove all mappings from a specific CC controller
Parameters
cc the MIDI CC number to unmap
References MidiParameterMapper::getMappingSettings().
getLastController()
int getLastController () const
Returns
the last touched MIDI controller so it can be mapped
Referenced by MagicProcessorState::getLastController().
getMappingSettings()
juce::ValueTree getMappingSettings ()
Grant access to the ValueTree to save or restore the mappings manually
Returns
the ValueTree containing the mappings
Referenced by MidiParameterMapper::mapMidiController(), MidiParameterMapper::unmapAllMidiController(), and MidiParameterMapper::unmapMidiController().
The documentation for this class was generated from the following files:
foleys_MidiParameterMapper.h
foleys_MidiParameterMapper.cpp