foleys_gui_magic: MagicGUIBuilder Class Reference
MagicGUIBuilder Class Reference
The MagicGUIBuilder is responsible to recreate the GUI from a single ValueTree.
#include <foleys_MagicGUIBuilder.h>
Inherits ChangeListener, and Listener.
Public Member Functions
MagicGUIBuilder (MagicGUIState &magicStateToUse)
~MagicGUIBuilder () override
std::unique_ptr< GuiItem > createGuiItem (const juce::ValueTree &node)
Create a node from the description.
void createGUI (juce::Component &parent)
This triggers the rebuild of the GUI with setting the parent component.
Stylesheet & getStylesheet ()
Grant access to the stylesheet to look up visual and layout properties.
juce::ValueTree & getConfigTree ()
Grants access to the main XML, that holds all information.
juce::ValueTree getGuiRootNode ()
Grants access to the GUI root node.
GuiItem * findGuiItemWithId (const juce::String &name)
Lookup a Component through the tree.
GuiItem * findGuiItem (const juce::ValueTree &node)
Seeks recursively for a GuiItem.
void updateStylesheet ()
This selects the stylesheet node and sets it to the Stylesheet.
void updateComponents ()
Recreates all components from the <View> tree.
void updateLayout ()
Recalculates the layout of all components.
void updateColours ()
Resolve all colours fresh, in case the palette has changed.
void registerFactory (juce::Identifier type, std::unique_ptr< GuiItem >(*factory)(MagicGUIBuilder &builder, const juce::ValueTree &))
Register a factory for Components to be available in the GUI editor.
void registerLookAndFeel (juce::String name, std::unique_ptr< juce::LookAndFeel > lookAndFeel)
With that method you can register your custom LookAndFeel class and apply it to different components.
void registerJUCELookAndFeels ()
Registers automatically the JUCE LookAndFeel classes (V1..V4 at the time of writing)
void registerJUCEFactories ()
Calling this method will register the bundled JUCE factories to give already access to many JUCE Components.
juce::var getStyleProperty (const juce::Identifier &name, const juce::ValueTree &node) const
This method traverses the dom and checks each style, if that property was defined.
void removeStyleClassReferences (juce::ValueTree tree, const juce::String &name)
This will go through all nodes and delete the reference to a class.
juce::StringArray getColourNames (juce::Identifier type)
This method returns the names of colours for a certain Component type.
void clearGUI ()
This resets the GUI to show a single empty container.
void showOverlayDialog (std::unique_ptr< juce::Component > dialog)
This is used to display a dialog box.
void closeOverlayDialog ()
Closes a possibly open overlay dialog.
juce::StringArray getFactoryNames () const
returns the names of all registered factories
std::function< void(juce::ComboBox &)> createChoicesMenuLambda (juce::StringArray choices) const
std::function< void(juce::ComboBox &)> createParameterMenuLambda () const
std::function< void(juce::ComboBox &)> createPropertiesMenuLambda () const
std::function< void(juce::ComboBox &)> createTriggerMenuLambda () const
template<typename ObjectType >
std::function< void(juce::ComboBox &)> createObjectsMenuLambda () const
RadioButtonManager & getRadioButtonManager ()
void changeListenerCallback (juce::ChangeBroadcaster *sender) override
void valueTreeRedirected (juce::ValueTree &treeWhichHasBeenChanged) override
juce::var getPropertyDefaultValue (juce::Identifier property) const
Lookup the default value of the property.
MagicGUIState & getMagicState ()
juce::UndoManager & getUndoManager ()
void attachToolboxToWindow (juce::Component &window)
void setEditMode (bool shouldEdit)
This method sets the GUI in edit mode, that allows to drag the components around.
bool isEditModeOn () const
void setSelectedNode (const juce::ValueTree &node)
const juce::ValueTree & getSelectedNode () const
void draggedItemOnto (juce::ValueTree dropped, juce::ValueTree target, int index=-1)
ToolBox & getMagicToolBox ()
Detailed Description
The MagicGUIBuilder is responsible to recreate the GUI from a single ValueTree.
You can add your own factories to the builder to allow additional components.
Constructor & Destructor Documentation
MagicGUIBuilder()
MagicGUIBuilder (MagicGUIState & magicStateToUse)
References MagicGUIBuilder::getConfigTree(), and MagicGUIBuilder::updateStylesheet().
~MagicGUIBuilder()
~MagicGUIBuilder () override
References MagicGUIBuilder::getConfigTree().
Member Function Documentation
createGuiItem()
std::unique_ptr< GuiItem > createGuiItem (const juce::ValueTree & node)
Create a node from the description.
References MagicGUIBuilder::getGuiRootNode().
Referenced by PropertiesEditor::addTypeProperties(), Container::createSubComponents(), MagicGUIBuilder::getColourNames(), and MagicGUIBuilder::updateComponents().
createGUI()
void createGUI (juce::Component & parent)
This triggers the rebuild of the GUI with setting the parent component.
References MagicGUIBuilder::updateComponents().
getStylesheet()
Stylesheet & getStylesheet ()
Grant access to the stylesheet to look up visual and layout properties.
Referenced by PropertiesEditor::addDecoratorProperties(), PropertiesEditor::addNodeProperties(), Decorator::configure(), PropertiesEditor::deleteClass(), GuiItem::GuiItem(), StylePropertyComponent::lookupValue(), PropertiesEditor::PropertiesEditor(), PropertiesEditor::setNodeToEdit(), ToolBox::stateWasReloaded(), StyleColourPropertyComponent::StyleColourPropertyComponent(), PlotItem::update(), GuiItem::updateColours(), Decorator::updateColours(), GuiItem::updateInternal(), and GuiItem::~GuiItem().
getConfigTree()
juce::ValueTree & getConfigTree ()
Grants access to the main XML, that holds all information.
References MagicGUIState::getGuiTree().
Referenced by MagicGUIBuilder::clearGUI(), MagicGUIBuilder::getGuiRootNode(), MagicGUIBuilder::MagicGUIBuilder(), ToolBox::saveGUI(), MagicGUIBuilder::updateStylesheet(), GUITreeEditor::updateTree(), and MagicGUIBuilder::~MagicGUIBuilder().
getGuiRootNode()
juce::ValueTree getGuiRootNode ()
Grants access to the GUI root node.
References MagicGUIBuilder::getConfigTree().
Referenced by PropertiesEditor::addNodeProperties(), MagicGUIBuilder::createGuiItem(), PropertiesEditor::deleteClass(), and MagicGUIBuilder::updateComponents().
findGuiItemWithId()
GuiItem * findGuiItemWithId (const juce::String & name)
Lookup a Component through the tree.
It will return the first with that id regardless if there is another one. We discourage using that function, because that Component can be deleted and recreated at any time without notice.
findGuiItem()
GuiItem * findGuiItem (const juce::ValueTree & node)
Seeks recursively for a GuiItem.
Referenced by MagicGUIBuilder::setSelectedNode().
updateStylesheet()
void updateStylesheet ()
This selects the stylesheet node and sets it to the Stylesheet.
If no stylesheet is found, a default one is created.
References MagicGUIBuilder::getConfigTree(), Stylesheet::setStyle(), Stylesheet::updateStyleClasses(), and Stylesheet::updateValidRanges().
Referenced by MagicGUIBuilder::MagicGUIBuilder(), and MagicGUIBuilder::updateComponents().
updateComponents()
void updateComponents ()
Recreates all components from the <View> tree.
If no div tree is found, createDefaultGUITree is called to give subclasses a chance to create a suitable default.
References MagicGUIBuilder::createGuiItem(), MagicGUIBuilder::getGuiRootNode(), and MagicGUIBuilder::updateStylesheet().
Referenced by MagicGUIBuilder::clearGUI(), MagicGUIBuilder::createGUI(), ToolBox::stateWasReloaded(), ToolBox::ToolBox(), and MagicGUIBuilder::valueTreeRedirected().
updateLayout()
void updateLayout ()
Recalculates the layout of all components.
References Stylesheet::setMediaSize(), and Stylesheet::updateValidRanges().
Referenced by MagicGUIBuilder::changeListenerCallback(), and MagicGUIBuilder::showOverlayDialog().
updateColours()
void updateColours ()
Resolve all colours fresh, in case the palette has changed.
registerFactory()
void registerFactory (juce::Identifier type, std::unique_ptr< GuiItem >(*)(MagicGUIBuilder &builder, const juce::ValueTree &) factory)
Register a factory for Components to be available in the GUI editor.
If you need a reference to the application, you can capture that in the factory lambda.
Referenced by MagicGUIBuilder::registerJUCEFactories().
registerLookAndFeel()
void registerLookAndFeel (juce::String name, std::unique_ptr< juce::LookAndFeel > lookAndFeel)
With that method you can register your custom LookAndFeel class and apply it to different components.
References Stylesheet::registerLookAndFeel().
registerJUCELookAndFeels()
void registerJUCELookAndFeels ()
Registers automatically the JUCE LookAndFeel classes (V1..V4 at the time of writing)
References Stylesheet::registerLookAndFeel().
Referenced by MagicProcessor::initialiseBuilder().
registerJUCEFactories()
void registerJUCEFactories ()
Calling this method will register the bundled JUCE factories to give already access to many JUCE Components.
References MagicGUIBuilder::registerFactory().
Referenced by MagicProcessor::initialiseBuilder().
getStyleProperty()
juce::var getStyleProperty (const juce::Identifier & name, const juce::ValueTree & node) const
This method traverses the dom and checks each style, if that property was defined.
Parameters
name the name of the property.
node is the node in the DOM. This is used for inheritance by traversing upwards.
References Stylesheet::getStyleProperty().
Referenced by Decorator::configure(), Container::configureFlexBox(), GuiItem::configureFlexBoxItem(), GuiItem::configurePosition(), GuiItem::getProperty(), TextButtonItem::update(), ToggleButtonItem::update(), LabelItem::update(), Container::update(), GuiItem::updateColours(), RootItem::updateColours(), and Decorator::updateColours().
removeStyleClassReferences()
void removeStyleClassReferences (juce::ValueTree tree, const juce::String & name)
This will go through all nodes and delete the reference to a class.
References MagicGUIBuilder::removeStyleClassReferences().
Referenced by PropertiesEditor::deleteClass(), and MagicGUIBuilder::removeStyleClassReferences().
getColourNames()
juce::StringArray getColourNames (juce::Identifier type)
This method returns the names of colours for a certain Component type.
References MagicGUIBuilder::createGuiItem().
clearGUI()
void clearGUI ()
This resets the GUI to show a single empty container.
References MagicGUIBuilder::getConfigTree(), and MagicGUIBuilder::updateComponents().
Referenced by ToolBox::ToolBox().
showOverlayDialog()
void showOverlayDialog (std::unique_ptr< juce::Component > dialog)
This is used to display a dialog box.
It is called by the GUI editor, but in future it might be reached using the configured GUI.
References MagicGUIBuilder::updateLayout().
Referenced by ToolBox::loadDialog(), and ToolBox::saveDialog().
closeOverlayDialog()
void closeOverlayDialog ()
Closes a possibly open overlay dialog.
Referenced by ToolBox::loadDialog(), and ToolBox::saveDialog().
getFactoryNames()
juce::StringArray getFactoryNames () const
returns the names of all registered factories
Referenced by PropertiesEditor::setNodeToEdit(), and Palette::update().
createChoicesMenuLambda()
std::function< void(juce::ComboBox &)> createChoicesMenuLambda (juce::StringArray choices) const
Referenced by SliderItem::getSettableProperties(), LabelItem::getSettableProperties(), and XYDraggerItem::getSettableProperties().
createParameterMenuLambda()
std::function< void(juce::ComboBox &)> createParameterMenuLambda () const
References MagicGUIState::createParameterMenu().
Referenced by SliderItem::getSettableProperties(), ComboBoxItem::getSettableProperties(), TextButtonItem::getSettableProperties(), ToggleButtonItem::getSettableProperties(), LabelItem::getSettableProperties(), and XYDraggerItem::getSettableProperties().
createPropertiesMenuLambda()
std::function< void(juce::ComboBox &)> createPropertiesMenuLambda () const
References MagicGUIState::populatePropertiesMenu().
Referenced by PropertiesEditor::addContainerProperties(), PropertiesEditor::addDecoratorProperties(), PropertiesEditor::addNodeProperties(), SliderItem::getSettableProperties(), TextButtonItem::getSettableProperties(), ToggleButtonItem::getSettableProperties(), and LabelItem::getSettableProperties().
createTriggerMenuLambda()
std::function< void(juce::ComboBox &)> createTriggerMenuLambda () const
References MagicGUIState::createTriggerMenu().
Referenced by TextButtonItem::getSettableProperties().
createObjectsMenuLambda()
template<typename ObjectType > std::function< void(juce::ComboBox &)> createObjectsMenuLambda () const
References MagicGUIState::getObjectIDsByType().
Referenced by PlotItem::getSettableProperties(), LevelMeterItem::getSettableProperties(), and ListBoxItem::getSettableProperties().
getRadioButtonManager()
RadioButtonManager & getRadioButtonManager ()
Grant access to the RadioButtonManager
Returns
the radioButtonManager
changeListenerCallback()
void changeListenerCallback (juce::ChangeBroadcaster * sender) override
References MagicGUIBuilder::updateLayout().
valueTreeRedirected()
void valueTreeRedirected (juce::ValueTree & treeWhichHasBeenChanged) override
References MagicGUIBuilder::updateComponents().
getPropertyDefaultValue()
juce::var getPropertyDefaultValue (juce::Identifier property) const
Lookup the default value of the property.
Referenced by Stylesheet::getStyleProperty(), and StylePropertyComponent::lookupValue().
getMagicState()
MagicGUIState & getMagicState ()
Referenced by GuiItem::getMagicState(), GuiItem::itemDragEnter(), GuiItem::itemDropped(), ToolBox::loadGUI(), and Stylesheet::updateStyleClasses().
getUndoManager()
juce::UndoManager & getUndoManager ()
Referenced by Stylesheet::addPaletteEntry(), StyleBoolPropertyComponent::refresh(), StyleChoicePropertyComponent::refresh(), StyleColourPropertyComponent::refresh(), StyleGradientPropertyComponent::refresh(), StyleTextPropertyComponent::refresh(), Stylesheet::setColourPalette(), StyleBoolPropertyComponent::StyleBoolPropertyComponent(), StyleColourPropertyComponent::StyleColourPropertyComponent(), StyleGradientPropertyComponent::StyleGradientPropertyComponent(), StylePropertyComponent::StylePropertyComponent(), and StyleTextPropertyComponent::StyleTextPropertyComponent().
attachToolboxToWindow()
void attachToolboxToWindow (juce::Component & window)
References MagicGUIState::getResourcesFolder().
setEditMode()
void setEditMode (bool shouldEdit)
This method sets the GUI in edit mode, that allows to drag the components around.
References MagicGUIBuilder::setSelectedNode().
Referenced by ToolBox::ToolBox().
isEditModeOn()
bool isEditModeOn () const
Referenced by GuiItem::paintOverChildren(), and GuiItem::updateInternal().
setSelectedNode()
void setSelectedNode (const juce::ValueTree & node)
References MagicGUIBuilder::findGuiItem().
Referenced by MagicGUIBuilder::setEditMode(), and ToolBox::setSelectedNode().
getSelectedNode()
const juce::ValueTree & getSelectedNode () const
Referenced by GuiItem::itemDropped(), ToolBox::keyPressed(), and GuiItem::paintOverChildren().
draggedItemOnto()
void draggedItemOnto (juce::ValueTree dropped, juce::ValueTree target, int index = -1)
Referenced by GuiItem::itemDropped(), and ToolBox::keyPressed().
getMagicToolBox()
ToolBox & getMagicToolBox ()
Referenced by StylePropertyComponent::mouseDoubleClick().
The documentation for this class was generated from the following files:
foleys_MagicGUIBuilder.h
foleys_MagicGUIBuilder.cpp
foleys_MagicJUCEFactories.cpp