foleys_gui_magic: ToolBox Class Reference
ToolBox Class Reference
The Toolbox defines a floating window, that allows live editing of the currently loaded GUI.
#include <foleys_ToolBox.h>
Inherits Component, DragAndDropContainer, KeyListener, and MultiTimer.
Public Types
enum PositionOption { left , right , detached }
Public Member Functions
ToolBox (juce::Component *parent, MagicGUIBuilder &builder)
Create a ToolBox floating window to edit the currently shown GUI.
~ToolBox () override
void loadDialog ()
void saveDialog ()
void loadGUI (const juce::File &file)
bool saveGUI (const juce::File &file)
void paint (juce::Graphics &g) override
void resized () override
void timerCallback (int timer) override
void setSelectedNode (const juce::ValueTree &node)
void setNodeToEdit (juce::ValueTree node)
void setToolboxPosition (PositionOption position)
void stateWasReloaded ()
bool keyPressed (const juce::KeyPress &key) override
bool keyPressed (const juce::KeyPress &key, juce::Component *originalComponent) override
void setLastLocation (juce::File file)
Static Public Member Functions
static juce::PropertiesFile::Options getApplicationPropertyStorage ()
Detailed Description
The Toolbox defines a floating window, that allows live editing of the currently loaded GUI.
Member Enumeration Documentation
PositionOption
enum PositionOption
Enumerator
left
right
detached
Constructor & Destructor Documentation
ToolBox()
ToolBox (juce::Component * parent, MagicGUIBuilder & builder)
Create a ToolBox floating window to edit the currently shown GUI.
The window will float attached to the edited window.
Parameters
parent is the window to attach to
builder is the builder instance that manages the GUI
References MagicGUIBuilder::clearGUI(), ToolBox::detached, ToolBox::getApplicationPropertyStorage(), ToolBox::left, ToolBox::loadDialog(), ToolBox::right, ToolBox::saveDialog(), MagicGUIBuilder::setEditMode(), ToolBox::setToolboxPosition(), ToolBox::stateWasReloaded(), and MagicGUIBuilder::updateComponents().
~ToolBox()
~ToolBox () override
Member Function Documentation
loadDialog()
void loadDialog ()
References MagicGUIBuilder::closeOverlayDialog(), and MagicGUIBuilder::showOverlayDialog().
Referenced by ToolBox::ToolBox().
saveDialog()
void saveDialog ()
References MagicGUIBuilder::closeOverlayDialog(), and MagicGUIBuilder::showOverlayDialog().
Referenced by ToolBox::ToolBox().
loadGUI()
void loadGUI (const juce::File & file)
References MagicGUIBuilder::getMagicState(), MagicGUIState::setGuiValueTree(), ToolBox::setLastLocation(), and ToolBox::stateWasReloaded().
saveGUI()
bool saveGUI (const juce::File & file)
References MagicGUIBuilder::getConfigTree().
Referenced by ToolBox::timerCallback().
paint()
void paint (juce::Graphics & g) override
resized()
void resized () override
timerCallback()
void timerCallback (int timer) override
References ToolBox::saveGUI().
setSelectedNode()
void setSelectedNode (const juce::ValueTree & node)
References PropertiesEditor::setNodeToEdit(), GUITreeEditor::setSelectedNode(), and MagicGUIBuilder::setSelectedNode().
setNodeToEdit()
void setNodeToEdit (juce::ValueTree node)
References PropertiesEditor::setNodeToEdit().
Referenced by StylePropertyComponent::mouseDoubleClick().
setToolboxPosition()
void setToolboxPosition (PositionOption position)
References ToolBox::detached.
Referenced by ToolBox::ToolBox().
stateWasReloaded()
void stateWasReloaded ()
References Stylesheet::getCurrentStyle(), MagicGUIBuilder::getStylesheet(), PropertiesEditor::setStyle(), Palette::update(), MagicGUIBuilder::updateComponents(), and GUITreeEditor::updateTree().
Referenced by ToolBox::loadGUI(), and ToolBox::ToolBox().
keyPressed() [1/2]
bool keyPressed (const juce::KeyPress & key) override
References MagicGUIBuilder::draggedItemOnto(), and MagicGUIBuilder::getSelectedNode().
Referenced by ToolBox::keyPressed().
keyPressed() [2/2]
bool keyPressed (const juce::KeyPress & key, juce::Component * originalComponent) override
References ToolBox::keyPressed().
getApplicationPropertyStorage()
juce::PropertiesFile::Options getApplicationPropertyStorage () static
Referenced by ToolBox::ToolBox().
setLastLocation()
void setLastLocation (juce::File file)
Referenced by ToolBox::loadGUI().
The documentation for this class was generated from the following files:
foleys_ToolBox.h
foleys_ToolBox.cpp