foleys_gui_magic: Palette Class Reference
Palette Class Reference
The Palette is the list of available components to be dragged into the tree or the GUI window.
#include <foleys_Palette.h>
Inherits Component.
Public Member Functions
Palette (MagicGUIBuilder &builder)
void paint (juce::Graphics &g) override
void resized () override
void update ()
Detailed Description
The Palette is the list of available components to be dragged into the tree or the GUI window.
To be able to drop into the GUI directly, the edit mode must be enabled.
Constructor & Destructor Documentation
Palette()
Palette (MagicGUIBuilder & builder)
References Palette::update().
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
resized()
void resized () override
update()
void update ()
References MagicGUIBuilder::getFactoryNames().
Referenced by Palette::Palette(), and ToolBox::stateWasReloaded().
The documentation for this class was generated from the following files:
foleys_Palette.h
foleys_Palette.cpp