name: foleys_gui_magic UnitTests

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * 1

defaults:
  run:
    shell: bash

jobs:

  build_and_test:

    name: ${{ matrix.os }} ${{ matrix.config }} tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        config: [Debug, Release]
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 1

    - name: Install JUCE's Linux Deps
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update && sudo apt install libasound2-dev libx11-dev libxinerama-dev \
        libxext-dev libfreetype6-dev libcurl4-openssl-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev \
        xvfb fluxbox ninja-build
        sudo /usr/bin/Xvfb $DISPLAY &

    - name: Configure CMake
      run: cmake --preset maintainer

    - name: Run build 
      run: cmake --build --preset maintainer --config ${{ matrix.config }}

    - name: Run tests 
      run: ctest --preset default

  ios_build:

    name: ${{ matrix.preset }} ${{ matrix.config }} build
    runs-on: macos-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false 
      matrix:
        preset: [iOS, tvOS, watchOS]
        config: [Debug, Release]
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Configure CMake
        run: cmake --preset ${{ matrix.preset }}

      - name: Run build 
        run: cmake --build --preset maintainer --config ${{ matrix.config }}

      # note: unit tests can't be run for iOS builds because 
      # Apple doesn't allow command-line executables to be built for iOS
